### ISSUE TITLE
Error unable to check Chart.yaml file in chart: stat 

### ISSUE THREAD

**Issue by TsixJnineY** [bitsbeats/drone-helm3#2]
Drone can't find path for Chart, I think drone went directly to find the path inside the container,bacause i setting wrong KUBE_API,but the drone shows that the path can't be found, instead it can't connect to the KUBE_API_SERVER.

    - name: helm-deploy
        image: bitsbeats/drone-helm3
        environment:
          KUBE_API_SERVER: https://masterIP:6443
          KUBE_TOKEN:
            from_secret: dev_kubernetes_token
        settings:
          mode: installupgrade
          chart: /home/team2/helm/mml
          release: app
          kube_service_account: admin-user
          wait: true
          values: image.tag=${DRONE_TAG}#
          values_files: ["./helm/app.yaml"]
          namespace: app
          skip_tls_verify: true

**Comment by foosinn** [comment]
>     environment:
>       KUBE_API_SERVER: https://masterIP:6443
>       KUBE_TOKEN:
>         from_secret: dev_kubernetes_token

these options should go into settings

>       chart: /home/team2/helm/mml

i asume that is the path on your local machine? you want to use a relative path like ./helm/mml

**Comment by TsixJnineY** [comment]
- name: helm-deploy
        image: bitsbeats/drone-helm3
        settings:
          KUBE_API_SERVER: https://masterIP:6443
          KUBE_TOKEN:
            from_secret: dev_kubernetes_token
          mode: installupgrade
          chart: ./helm/mml
          release: mml-dev
          kube_service_account: admin-user
          wait: true
          values: image.tag=${DRONE_TAG}#
          values_files: ["./helm/mml/values.yaml"]
          namespace: mml-dev
          skip_tls_verify: true

Yes, I have set it up according to your method, but still shows that the chart path can't be found helm/mml/Chart.yaml.
My Chart.yaml is in the /helm/mml path.

**Comment by foosinn** [comment]
the path should be relative to your git root.

>       KUBE_API_SERVER: https://masterIP:6443
>       KUBE_TOKEN:
>         from_secret: dev_kubernetes_token

you can lowercase them. drone has some documentation how these settings work.
