### ISSUE TITLE
Kubernetes configuration file is group-readable. This is insecure.

### ISSUE THREAD

**Issue by cicdteam** [bitsbeats/drone-helm3#4]
Hi !

kubeconfig file created [there](https://github.com/bitsbeats/drone-helm3/blob/master/internal/kube/kube.go#L106) by `os.Create()`

but regarding the doc:

>Create creates or truncates the named file. If the file already exists, it is truncated. If the file does not exist, it is created with mode 0666 (before umask). 

And we have such warnings:

>WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config

Can you add [os.Chmod](https://golang.org/pkg/os/#File.Chmod) as well ?

**Comment by foosinn** [comment]
Thanks a lot for noticing!

Fixed by f5b3befa8cef8f083fe257971f608257c00dd7e9
